site_name: Bioinformatics
theme: yeti
nav:

- Shell:
        - Basics/Hacking:
              - Commands: shell/shell.md
              - Cloud Computing: shell/shell_adv.md
              - Ubuntu Server: shell/ubuntu_server.md
              - GPUs: shell/gpu.md
        - File Manipulation (fasta): shell/fasta.md
        - Git: shell/git.md
- Python:
        - Basics: python/python.md
        - Bioconda: python/bioconda.md
- R:
        - Basics: R/R.md
        - Graphics:
              - ggplot: R/ggplot.md
              - heatmap: R/distanceheatmap.md
- Tools:
        - Atom Editor: tools/atom.md
        - EMBOSS: tools/emboss.md
        - mkdocs: tools/mkdocs.md
        - UGENE: tools/UGENE.md
- Sequencing:
        - Programs: sequencing/programs.md
        - HTS (Illumina): sequencing/illumina.md
        - Longreads (Nanopore): sequencing/nanopore.md
        - Hybridassembly: sequencing/hybrid.md
        - Annotation: sequencing/annotation.md
- Metagenome:
        - Metagenomics: metagenome/metagenomics.md
        - Metabarcoding: metagenome/metabarcoding.md
- Docker:
        - Docker-Basics: docker/docker.md
        - Docker in Win: docker/win_docker.md
        - GPU_Docker: docker/gpu.md
- Other Topics:
        - Databases: other_topics/databases.md
        - GWAS: other_topics/gwas.md
        - GS: other_topics/gs.md
        - RNA seq: other_topics/RNA_seq.md
