site_name: Bioinformatics
theme: yeti
nav:
- Home: index.md
- Databases:
        - General: databases.md
        - EMBOSS: emboss.md
- Shell:
        - Basics: shell.md
        - Fasta_Manipulation: fasta.md
- Python:
        - Basics: python.md
- Tools:
        - Atom Editor: atom.md
        - mkdocs: mkdocs.md
