site_name: Bioinformatics
theme: yeti
nav:
- Home: index.md
- Databases:
        - General: databases.md
        - EMBOSS: emboss.md
- Shell:
        - Basics: shell.md
        - Fasta Manipulation: fasta.md
        - Advanced Commands & Installation: shell_adv.md
        - Git: git.md
- Python:
        - Basics: python.md
- R:
        - R: R.md
- Tools:
        - Atom Editor: atom.md
        - mkdocs: mkdocs.md
- Sequencing:
        - Programms: programs.md
        - HTS (Illumina): illumina.md
        - Longreads (Nanopore): nanopore.md
        - Hybridassembly: hybrid.md
- Other Topics:
        - GWAS: gwas.md
        - GS: gs.md
